### ISSUE TITLE
how to prepared the input file and reference file 

### ISSUE THREAD

**Issue by moshl** [faryabib/HeatITup#1]
Hi, I collected some FLT3-ITD from published paper (Gregory W. Schwartz 2018 CCR), then I input sequence information of ITD(just inserted sequence), and make a simple reference file about common region included chr13  - 28607918-28608417. 
the code: 
./heatitup -i TCGA-FLT3-ITD-heatITup-input.txt -I Hg19-FLT3-ITD-PCRregion-heatITup-ref.txt --min-size 1 --min-mutations 1

but the results is very stranger:
,CCR-Atypical,CAATTTAGGTATGAAAGCCACCTTCGTTTAGGTATGAAG,CAATTTAGGTATGAAG,1/24,1/24,,,,Typical
,CCR-typical,CAATTTAGGTATGAATTTAGGTATGAAAGCCAGCTACAG,CAATTTAGGTATGAAA,1/17,1/16,,,,Typical

from the paper ,the first is  atypical and the second is typical 

Why I get a fault result ? how to prepared the input file and reference file ?

**Comment by GregorySchwartz** [comment]
When you want to characterize the spacer, you need to supply the `--spacer` argument. The program will then compare the `--reference-field` in the header of the input to that ID in the `--reference-input`. For instance:

input.fasta:
```
>1|ref
CAATTTAGGTATGAAAGCCACCTTCGTTTAGGTATGAAG
>2|ref
CAATTTAGGTATGAATTTAGGTATGAAAGCCAGCTACAG
```

reference.fasta:
```
>ref
CAATTTAGGTATGAAAGCCAGCTACAGATGGTACAGGTGACCGGCTCCTCAGATAATGAG
TACTTCTACGTTGATTTCAGAGAATATGAATATGATCTCAAATGGGAGTTTCCAAGAGAA
AATTTAGAGTTTG                                              
```

```
cat ./input.fasta | heatitup --min-size 6 --reference-input ./reference.fasta --reference-field 2 --spacer
label,fHeader,fSequence,dSubstring,dLocations,dMutations,sSubstring,sLocation,sOtherLocations,classification
,1|ref,CAATTTAGGTATGAAAGCCACCTTCGTTTAGGTATGAAG,TTTAGGTATGAA,4/27,,AGCCACCTTCG,16,24/25,Atypical
,2|ref,CAATTTAGGTATGAATTTAGGTATGAAAGCCAGCTACAG,TTTAGGTATGAA,4/16,,,,,Typical
```

The `gaussian` and other settings were set for what we observed for much larger reads, so for examples this small they would have to be adjusted accordingly to get precise locations of the exogenous nucleotides.
Let me know if it worked for you!

**Comment by GregorySchwartz** [comment]
Added this example in https://github.com/faryabib/HeatITup/commit/27aad7350c0e117fa9f36644c8c86261afa10893

**Comment by GregorySchwartz** [comment]
Closing as issue should be resolved.
